import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/signup');
//   await page.getByRole('link', { name: 'Website for automation' }).click();
//   await page.getByRole('link', { name: ' Signup / Login' }).click();
//   await page.getByRole('textbox', { name: 'Name' }).click();
//   await page.getByRole('textbox', { name: 'Name' }).fill('sriman');
//   await page.getByRole('textbox', { name: 'Name' }).press('Tab');
//   await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('goodfellas@gmail.com');
//   await page.getByRole('button', { name: 'Signup' }).click();
//   await page.getByRole('radio', { name: 'Mr.' }).check();
//   await page.getByRole('textbox', { name: 'Password *' }).click();
//   await page.getByRole('textbox', { name: 'Password *' }).fill('GoodFellas');
//   await page.locator('#days').selectOption('15');
//   await page.locator('#months').selectOption('3');
//   await page.locator('#years').selectOption('2000');
//   await page.getByRole('textbox', { name: 'First name *' }).click();
//   await page.getByRole('textbox', { name: 'First name *' }).fill('sriman');
//   await page.getByRole('checkbox', { name: 'Sign up for our newsletter!' }).check();
//   await page.getByRole('checkbox', { name: 'Receive special offers from' }).check();
//   await page.getByRole('textbox', { name: 'Last name *' }).click();
//   await page.getByRole('textbox', { name: 'Last name *' }).fill('M');
//   await page.getByRole('textbox', { name: 'Last name *' }).press('Tab');
//   await page.getByRole('textbox', { name: 'Company', exact: true }).fill('abc');
//   await page.getByRole('textbox', { name: 'Company', exact: true }).press('Tab');
//   await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('4st avadi');
//   await page.getByRole('textbox', { name: 'State *' }).click();
//   await page.getByRole('textbox', { name: 'State *' }).fill('Tamilnadu');
//   await page.getByRole('textbox', { name: 'State *' }).press('Tab');
//   await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('chennai');
//   await page.getByRole('textbox', { name: 'City * Zipcode *' }).press('Tab');
//   await page.locator('#zipcode').fill('600072');
//   await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
//   await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('9876543210');
//   await page.getByRole('button', { name: 'Create Account' }).click();
//   await page.getByRole('link', { name: 'Continue' }).click();
//   await page.getByRole('link', { name: ' Logout' }).click();
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').fill('goodfellas@gmail.com');
  await page.locator('form').filter({ hasText: 'Login' }).getByPlaceholder('Email Address').press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('GoodFellas');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: ' Products' }).click();
  await page.getByRole('heading', { name: ' Kids' }).click();
  await page.getByRole('link', { name: '(3) Allen Solly Junior' }).click();
  await page.getByRole('link', { name: ' View Product' }).nth(1).click();
  await page.locator('#quantity').click();
  await page.locator('#quantity').dblclick();
  await page.locator('#quantity').fill('3');
  await page.getByRole('button', { name: ' Add to cart' }).click();
  await page.getByRole('button', { name: 'Continue Shopping' }).click();
  await page.getByRole('link', { name: ' Products' }).click();
  await page.getByRole('textbox', { name: 'Search Product' }).click();
  await page.getByRole('textbox', { name: 'Search Product' }).fill('Fancy Green Top');
  await page.getByRole('textbox', { name: 'Search Product' }).press('Enter');
  await page.locator('#submit_search').click();
  await page.getByText('Add to cart').nth(1).click();
  await page.getByRole('link', { name: 'View Cart' }).click();
  await page.getByText('Proceed To Checkout').click();
  await page.getByRole('link', { name: 'Place Order' }).click();
  await page.locator('input[name="name_on_card"]').click();
  await page.locator('input[name="name_on_card"]').fill('sriman');
  await page.locator('input[name="name_on_card"]').press('Tab');
  await page.locator('input[name="card_number"]').fill('9876543211234567');
  await page.getByRole('textbox', { name: 'ex.' }).click();
  await page.getByRole('textbox', { name: 'ex.' }).fill('311');
  await page.getByRole('textbox', { name: 'ex.' }).press('Tab');
  await page.getByRole('textbox', { name: 'MM' }).fill('23');
  await page.getByRole('textbox', { name: 'MM' }).press('Tab');
  await page.getByRole('textbox', { name: 'YYYY' }).fill('2028');
  await page.getByRole('button', { name: 'Pay and Confirm Order' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download Invoice' }).click();
  const download = await downloadPromise;
  await page.screenshot({path:'addtocart.png',fullpage:true})
  await page.getByRole('link', { name: 'Continue' }).click();
});